Fixed wording
rhochgraf21/Constitution pull request #112
Opened 2023-10-29 22:00 UTC by esoccoli

Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [X] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):
Resolve #78

2023-10-30 00:05 UTC, rhochgraf21 requested changes

2023-10-30 00:05 UTC, rhochgraf21 commented on constitution.tex
> +The Computer Science House shall recognize that it receives its right to function as a Special Interest House from the Center for Student Development.
Center for Campus Life, perhaps?

2023-10-31 01:12 UTC, esoccoli commented
Made requested changes

2023-11-06 04:05 UTC, danisaba commented on constitution.tex
> +The Computer Science House shall recognize that it receives its right to function as a Special Interest House from the Center for Student Development.
I prefer "Student Development Center" as per RIT links. I do not see any official RIT center for campus life. Robert, why suggest this change?

Check links below:
Student Development Center: https://www.rit.edu/facilitiesmanagement/building/student-development-center
Campus Life: https://www.rit.edu/studentlife/campus-life
Residence Life: https://www.rit.edu/studentlife/residence-life

2023-11-06 04:08 UTC, danisaba requested changes
see conversation on this where I linked campus resources per Robert's requested change

2023-11-06 05:01 UTC, danisaba approved these changes

2023-11-06 05:10 UTC, danisaba requested changes
We get club rules from the center for campus life and living rules from Reslife. Therefore they have authority and they both need to be mentioned so this needs to be changed

2024-01-27 21:57 UTC, Sam-Cordry approved these changes
Looks good to me now.

2024-01-30 03:28 UTC, merged