Condensed bulleted list of maintainer expectations
rhochgraf21/Constitution pull request #115
Opened 2023-10-29 22:10 UTC by esoccoli

Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):
Resolve #84

2023-10-30 00:10 UTC, rhochgraf21 approved these changes
I like the idea that Maintainers are expected to keep public record of changes.

2023-10-30 00:10 UTC, rhochgraf21 commented on constitution.tex
> -	\item Keep a public record of changes to the Constitution
I like this requirement/expectation, personally. Candidate for keeping it?

2023-10-30 00:17 UTC, rhochgraf21 requested changes
whoops this should be

2023-10-31 01:10 UTC, esoccoli commented
Made requested changes

2023-10-31 02:31 UTC, rhochgraf21 commented
👍

2023-10-31 02:31 UTC, rhochgraf21 approved these changes

2023-10-31 02:31 UTC, merged