resolve #37 - VOTING AMENDMENT 🎉
rhochgraf21/Constitution pull request #135
Opened 2023-11-22 02:13 UTC by rhochgraf21

Check one:
- [X] Semantic Change: something about the meaning of the text is different.
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):

- Definitions for Voting have been updated. "Total Number of Possible Votes" -> "Eligible Votes", and the like.
- "Alternative Vote" is no longer described as a Method of Vote as well as a means of counting votes; it is now only a means of counting votes. Also it's been renamed to "Ranked Choice".
- Imposed quorum requirements for votes that had previously been missing quorums.
- Replaced Every™ vote in the Constitution with new format.

Resolves #37

2023-12-06 00:23 UTC, danisaba requested changes
I think I made one nitpicky change. I also want to discuss the word "ballot" and its use. Also want to discuss dual directorships as mentioned. Anyways read my comments and prepare for sad

2023-12-06 00:23 UTC, danisaba commented on constitution.tex
> +In order for an Active Member to be eligible to vote during the evaluation process they must meet the requirements outlined in \ref{Expectations of Voting Members}.
This is just me being nitpicky, but "In order for" doesn't need to exist. "For an Active Member to be eligible to vote during the evaluation process...." etc etc

2023-12-06 00:23 UTC, danisaba commented on constitution.tex
> +	\item Dual directorships must have both members present for to count towards Quorum in an Executive Board Vote.
is this a true statement that reflects current practice?

2023-12-06 00:23 UTC, danisaba commented on constitution.tex
> +	\item At the end of the voting period, the Chairperson will terminate voting by collecting the ballot box.
We do not use a ballot box anymore. So I am not sure how to update this to reflect current practices though I feel we should

2024-01-24 00:13 UTC, Sam-Cordry commented on constitution.tex
>  The sum of the number of Active members eligible to vote on the issue.
Change to "The number of Active...".

2024-01-24 00:14 UTC, Sam-Cordry commented on constitution.tex
> +The sum of the number of votes, excluding Abstentions.
"The number of votes cast, excluding Abstentions."

2024-01-24 00:16 UTC, Sam-Cordry commented on constitution.tex
> +A quorum is expressed as a fraction or percentage of Eligible Votes (rounded up) unless otherwise specified.
"...Eligible Votes (rounded up to the nearest vote) unless..."

2024-01-24 00:28 UTC, rhochgraf21 commented on constitution.tex
>  \asubsection{Proxy Ballot}
Proxy Vote

2024-01-24 00:41 UTC, Sam-Cordry commented on constitution.tex
>  When a Batch Vote is called for by the Chair of the Vote, a subset of the voting docket may be amended to a single vote.
"Chair of the Vote, a non-empty subset"

2024-01-24 00:43 UTC, Sam-Cordry commented on constitution.tex
>  If not, the option with the fewest number of first preference votes is eliminated and their votes move to the second preference marked on the ballot papers.
Nuke "papers".

2024-01-24 00:50 UTC, Sam-Cordry commented on constitution.tex
> +In the event of a tie in an Executive Board Vote, the Chairperson may cast the tie-breaking vote.
"the Chairperson casts the tie-breaking vote."(?)

2024-01-27 20:23 UTC, rhochgraf21 commented on constitution.tex
> +In order for an Active Member to be eligible to vote during the evaluation process they must meet the requirements outlined in \ref{Expectations of Voting Members}.
fixed

2024-01-27 20:29 UTC, rhochgraf21 commented on constitution.tex
> +	\item Dual directorships must have both members present for to count towards Quorum in an Executive Board Vote.
no, it is not.

2024-01-27 20:31 UTC, rhochgraf21 commented on constitution.tex
> +	\item At the end of the voting period, the Chairperson will terminate voting by collecting the ballot box.
fixed.

2024-01-27 20:32 UTC, rhochgraf21 commented on constitution.tex
>  The sum of the number of Active members eligible to vote on the issue.
👍

2024-01-27 20:36 UTC, rhochgraf21 commented on constitution.tex
> +The sum of the number of votes, excluding Abstentions.
fix'd

2024-01-27 20:37 UTC, rhochgraf21 commented on constitution.tex
> +A quorum is expressed as a fraction or percentage of Eligible Votes (rounded up) unless otherwise specified.
🥇

2024-01-27 20:46 UTC, rhochgraf21 commented on constitution.tex
>  \asubsection{Proxy Ballot}
👍

2024-01-27 20:48 UTC, rhochgraf21 commented on constitution.tex
>  The Chair of the Vote is a vote counter and will additionally select two other members to count votes.
👍

2024-01-27 20:55 UTC, rhochgraf21 commented
ready for review

2024-01-27 21:07 UTC, Sam-Cordry approved these changes
After implementing feedback from discussion, this looks good to me.

2024-01-27 22:41 UTC, esoccoli requested changes
For an on floor vote to, it should be changed to say that it is a vote among attending members. Also, mention something about how the evals director may decide there arent enough people present to vote

2024-01-27 22:41 UTC, esoccoli commented on constitution.tex
> +The Evaluations Director will then bring them up for a One-Half Immediate vote with twenty-five percent Quorum at the next evaluations meeting.
This should be changed to say that it is a vote among attending members. Also, mention something about how the evals director may decide there arent enough people present to vote

2024-02-07 00:39 UTC, Sam-Cordry commented
@rhochgraf21 Here you go.

2024-02-21 00:40 UTC, rhochgraf21 commented on constitution.tex
> +The Evaluations Director will then bring them up for a One-Half Immediate vote with twenty-five percent Quorum at the next evaluations meeting.
changed 👍

2024-02-21 00:41 UTC, rhochgraf21 commented
@esoccoli updated with the changes you noted

2024-02-28 00:32 UTC, esoccoli approved these changes
lgtm

2024-02-28 01:05 UTC, danisaba approved these changes
Looks good to me.

2024-03-03 21:04 UTC, merged