Resolve #146 - 7.D Added new clause to require all Judicials to be recorded
rhochgraf21/Constitution pull request #148
Opened 2024-01-27 22:50 UTC by IgorPolotai

Check one:
- [X] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s): Added a new 7.D Judicial Record Clause, that requires all Judicials to record the context, vote split, outcome, and optionally reasoning of Eboard members of all Judicials, and gives Eboard the ability to instead record the Judicial in a private document with a Simple Majority Vote (however, the content requirements are the same).

2024-01-27 22:55 UTC, mxmeinhold requested changes

2024-01-27 22:55 UTC, mxmeinhold commented on .gitignore
> +.vs/Constition Repo/v17/.wsuo
These should probably be added to your personal ignore files instead

2024-01-27 22:55 UTC, mxmeinhold commented on constitution.tex
> +All Judicials must be recorded in a public document accessible to all Active Members and Alumni by an Executive Board member. Judicial Records must include the context, vote split, and outcome, and o
Format: one sentance per line please

2024-01-27 23:06 UTC, esoccoli commented
I think the content is fine, but the wording should be changed. I would suggest changing the wording to "The Executive Board must record records of all Judicials in a location that all members can access. These records must include the context, vote split, and outcome. If it is deemed necessary, the Executive Board may choose, through a Simple Majority Vote, to move the Judicial Record to a private document that is only accessible by the Executive Board"

2024-01-27 23:07 UTC, esoccoli commented on constitution.tex
> +All Judicials must be recorded in a public document accessible to all Active Members and Alumni by an Executive Board member. Judicial Records must include the context, vote split, and outcome, and o
I think the content is fine, but the wording should be changed. I would suggest changing the wording to "The Executive Board must record records of all Judicials in a location that all members can access. These records must include the context, vote split, and outcome. If it is deemed necessary, the Executive Board may choose, through a Simple Majority Vote, to move the Judicial Record to a private document that is only accessible by the Executive Board"

2024-01-27 23:09 UTC, esoccoli commented
This PR contains changes made in a different PR. Make sure to rebase so there is only 1 change per PR

2024-02-03 22:59 UTC, esoccoli commented
This will be handled in its own amendment, after we finish the rewrite

2024-02-07 00:27 UTC, Sam-Cordry commented
Closing per discussion in meeting. Will come back to this as its own amendment at a later time.

2024-02-07 00:27 UTC, closed without merging