Resolves #72 Gives Ad Hocs Their Own Section (Again)
rhochgraf21/Constitution pull request #160
Opened 2024-03-06 00:34 UTC by Sam-Cordry

Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):
Resolves #72 by adding in a section for Ad Hoc Directorships in Article 5 and refactoring some content around it (again).

2024-03-06 00:38 UTC, danisaba requested changes
change it. (love u sam)

2024-03-06 00:38 UTC, danisaba commented on constitution.tex
> +They are generally task-oriented and are chaired by a House member(s).
This and the line below about them being "active members" should go in a section titled "qualifications of adhoc..." just like the eboard positions to have CONSISTENCYYYYYYY RAAAHHH

2024-03-06 00:38 UTC, danisaba commented on constitution.tex
> +	\item When the Ad Hoc Directorship is granted status, a director is appointed, and duties, budgetary, and membership considerations are defined.
make two sentences. I don't like the word budgetary :pleading_face:

2024-03-06 00:38 UTC, danisaba commented on constitution.tex
> +Candidates for being Ad Hoc Directors must be Active Members.
see above comment

2024-03-06 00:57 UTC, rhochgraf21 commented on constitution.tex
> +% This is implied, but Ad Hoc Directorships are not intended to be restricted to single or dual directorship rules.
In my opinion, this is best said explicitly

2024-04-07 00:28 UTC, esoccoli commented
Decided to pursue this in a separate amendment later

2024-04-07 00:28 UTC, closed without merging