136 removing dry notes
rhochgraf21/Constitution pull request #163
Opened 2024-03-07 20:20 UTC by ikopke23

Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):

removes 'note' and 'additional note' from 5.D.2.B.1 and 5.D.2.B.2, (4.A.2.A.1 and .2)

those notes are now under 4.A.2.A

2024-03-08 15:29 UTC, danisaba requested changes

2024-03-08 15:29 UTC, danisaba commented on constitution.tex
> -Note: Most membership privileges do not initiate until successful completion of the introductory process.
why were there two :sob:

2024-03-08 15:29 UTC, danisaba commented on constitution.tex
> -Before the end of the Process, an Introductory Member is expected to:
what happened here?

2024-03-08 15:29 UTC, danisaba commented on constitution.tex
> +Any modifications made due to the discussion are added to the written proposal and the modified proposal is posted in the House during the week.
i am also not sure what happened here

2024-03-08 18:01 UTC, ikopke23 commented
saying what my recent commit said but I nuked my constitution.tex and restarted. 

All my skill issues that I assume happened as I was still learning how the fuck nvim worked have disappeared. The only difference should now pertain to the initial PR.

2024-03-19 18:35 UTC, danisaba approved these changes
Looks good to me.

2024-03-19 23:46 UTC, esoccoli approved these changes
Lgtm

2024-03-26 21:32 UTC, merged