Removed Section formerly 5.D.2.A.4.C, Alternate Housing, which violates RIT housing
rhochgraf21/Constitution pull request #20
Opened 2023-08-26 05:17 UTC by Loerb01

Check one:
- [X] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):

Section formerly 5.D.2.A.4.C, Alternate Housing, is removed to reflect current practice and comply with RIT Housing, which resolves #2.

2023-09-03 18:10 UTC, rhochgraf21 requested changes
removing three tiered vote made it into this pr. other than that, looks good

2023-09-03 18:10 UTC, rhochgraf21 commented on constitution.tex
> -\asubsection{Three Tiered}
Looks like removing Three Tiered voting made it into this PR. Undoing deleting these lines may be a good idea

2023-09-03 18:10 UTC, rhochgraf21 commented on constitution.tex
> -		In addition, the participant is asked to find alternative housing as soon as possible in accordance with all applicable Residence Life policies regarding room changes.
👍

2023-09-26 21:10 UTC, Sam-Cordry commented on constitution.tex
> -\asubsection{Three Tiered}
I went ahead and re-added Three Tiered voting to this PR.

2023-10-09 04:02 UTC, rhochgraf21 approved these changes

2023-10-09 04:03 UTC, merged