Drafted abbreviations section
rhochgraf21/Constitution pull request #55
Opened 2023-09-25 18:33 UTC by esoccoli

Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [X] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):
Wrote a first draft of an abbreviations section. I intend to bring this up for discussion during tomorrows meeting (9/26/23).

2023-10-28 04:12 UTC, rhochgraf21 requested changes
hoping this doesn't give you 18 emails :(
see review notes

2023-10-28 04:12 UTC, rhochgraf21 commented on constitution.tex
> +Note: Most membership privileges do not initiate until successful completion of the intro process.
capitalize Intro Process?

2023-10-28 04:12 UTC, rhochgraf21 commented on constitution.tex
> +To initiate an appeal, a member must have the support of three voting E-Board members, or a petition with the signatures of one-third of Active Members.
capitalize members

2023-10-28 22:09 UTC, esoccoli commented
I am going to resolve all the things that I intentionally didn't change, but I am open to discussion

2023-10-28 22:10 UTC, esoccoli commented on constitution.tex
> +
Are you referring to the newline? If so i can look at it, but I dont think that is a necessary change for merging this

2023-10-28 22:14 UTC, esoccoli commented
Can we push the some of these changes off and put them in the spelling and grammar megathread? I am fine with changing it, but I don't think this PR is the right place because all of my changes keep the same capitalization as the current version

2023-10-28 22:47 UTC, esoccoli commented on constitution.tex
> +The intro evals process is described in \ref{Introductory Evaluation}.
I would say pluralized

2023-10-28 22:58 UTC, esoccoli commented
Made all the requested changes, and also added newlines after each section to make it easier to find things in the document. 

These newlines can be removed later, but for working on changes, it is very difficult to read the latex document when there are giant groups of like 20 lines of text with no line break

2023-10-30 00:15 UTC, rhochgraf21 commented
I think this looks good. This is a large enough commit that a second reviewer would be a good idea. @Sam-Cordry ?

2023-12-06 00:31 UTC, danisaba commented on constitution.tex
> +The intro evals process is described in \ref{Introductory Evaluation}.
I feel like it should be plural for mentions where its plural, and singular in cases where its not. I think we already talked about this and got agreement during a meeting earlier this semester regarding this as well

2024-01-27 21:04 UTC, Sam-Cordry approved these changes
Looks good for now; we'll probably and more to this section later as we flesh out what we think should go here

2024-01-27 21:11 UTC, rhochgraf21 approved these changes

2024-01-30 03:48 UTC, merged