Clarify Resignation of Chair
rhochgraf21/Constitution pull request #57
Opened 2023-09-26 21:25 UTC by Sam-Cordry

Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):
This PR aims to fix the issue with the resignation of a Chairperson in #38.

2023-09-26 21:42 UTC, mxmeinhold commented on constitution.tex
> +If at any point during the resignation, selections, or appointment of an interim director processes there is not an acting Chairperson, then the Evaluations Director assumes the responsibilities and
Would it be simpler to generally state that should there not be a chair, evals serves as acting chair, in the same way we state that lacking a director the chair is acting?

2023-10-09 03:56 UTC, rhochgraf21 requested changes
I think it would be a good idea to additionally a line of succession. I propose Chair -> Evals -> Financials -> E-Board Member Chosen by Majority Vote of Voting E-Board Members. I also agree with the above comment, it is probably simpler to use "Acting chair" tye language.

2024-02-13 21:15 UTC, Sam-Cordry commented
This particular change is a bit more a draft proposal than a final one because of how quickly this was made. I want more people to look at it for formatting, content, and if it just makes sense.

2024-02-28 00:38 UTC, esoccoli commented
@Sam-Cordry

2024-03-05 23:04 UTC, esoccoli approved these changes
lgtm

2024-03-07 19:48 UTC, danisaba approved these changes
slay

2024-03-19 20:11 UTC, rhochgraf21 submitted a review, later dismissed
sorry :(

2024-03-19 20:11 UTC, rhochgraf21 commented on constitution.tex
> +If at any point during the resignation, selections, or appointment of an interim director there is not a an acting Chairperson, then the following list is used to determine the who becomes the acting
a an => an

2024-03-19 20:11 UTC, rhochgraf21 commented on constitution.tex
> -
needed?

2024-03-19 20:11 UTC, rhochgraf21 commented on constitution.tex
> +If at any point during the resignation, selections, or appointment of an interim director there is not a an acting Chairperson, then the following list is used to determine the who becomes the acting
this wording is vague. 

"the following line of succession..." would be a good replacement for "the following list"

probably a good idea to say: if a position is vacant, it is not a possibility to become an acting chair

2024-03-19 20:11 UTC, rhochgraf21 commented on constitution.tex
> +If at any point during the resignation, selections, or appointment of an interim director there is not a an acting Chairperson, then the following list is used to determine the who becomes the acting
Are there any other scenarios which we would want an Acting Chairperson? For example, _elections_? Do we want/need to limit this to only interim directors?

2024-03-26 21:35 UTC, esoccoli commented
@Sam-Cordry

2024-03-26 21:42 UTC, ikopke23 commented on constitution.tex
> +If at any point during the resignation, selections, or appointment of an interim director there is not a an acting Chairperson, then the following list is used to determine the who becomes the acting
Chair could be unable to perform the duties of chair, like being sick/in the hospital/family emergency, and might not have wanted to resign so there might be a reason for acting chair if the chair needs time to recoup or something similar. 

I think that limiting the document to not have an acting chair could eventually due to some circumstances unforeseen to us now come back and haunt us.

2024-03-26 21:43 UTC, ikopke23 commented on constitution.tex
> -
I personally didn't like that line

2024-03-26 21:47 UTC, ikopke23 commented on constitution.tex
> +If at any point during the resignation, selections, or appointment of an interim director there is not a an acting Chairperson, then the following list is used to determine the who becomes the acting
I would suggest "the following line of succession is used to determine which director becomes the acting Chairperson until a new Chairperson is elected" mainly because I don't like "is used to determine the who becomes ..."

That might be personal preference but it seems clunky to me

2024-04-07 21:29 UTC, esoccoli approved these changes
lgtm

2024-04-07 22:55 UTC, merged