Resolve #67 4.B.4 Remove Last Paragraph
rhochgraf21/Constitution pull request #74
Opened 2023-10-26 03:17 UTC by GODWSY1

Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):
Resolves #67 by removing last paragraph about voting exemptions for Active members on co-op in 4.B.4.

2023-10-27 01:17 UTC, rhochgraf21 commented on constitution.tex
> +Evaluations \& Selections & 5\% \\
Guessing this wasn't intended to be in this commit?

2023-10-27 01:21 UTC, rhochgraf21 requested changes
I recommend rebasing the main branch in order to remove some artifacts from this commit.

2023-10-27 01:21 UTC, rhochgraf21 commented on constitution.tex
> +This figure is based on yearly estimated on-floor member dues (\$160 x 72 members = \$11520) minus the 10\% reserved for Accumulated (Accum).
Same as above?

2023-10-27 01:21 UTC, rhochgraf21 commented on constitution.tex
> +		In addition, the participant is asked to find alternative housing as soon as possible in accordance with all applicable Residence Life policies regarding room changes.
ditto

2023-10-27 01:21 UTC, rhochgraf21 commented on constitution.tex
> +
ditto

2023-10-27 01:21 UTC, rhochgraf21 commented on constitution.tex
> -Exceptions may be made at the discretion of the Evaluations Director.
👍

2023-10-28 21:57 UTC, Sam-Cordry commented on constitution.tex
> +Evaluations \& Selections & 5\% \\
Updated document to fix this.

2023-10-28 21:57 UTC, Sam-Cordry commented on constitution.tex
> +This figure is based on yearly estimated on-floor member dues (\$160 x 72 members = \$11520) minus the 10\% reserved for Accumulated (Accum).
Updated document fix this.

2023-10-28 21:57 UTC, Sam-Cordry commented on constitution.tex
> +		In addition, the participant is asked to find alternative housing as soon as possible in accordance with all applicable Residence Life policies regarding room changes.
Updated document fix this.

2023-10-28 21:58 UTC, Sam-Cordry commented on constitution.tex
> +
Updated document fix this.

2023-10-28 21:58 UTC, Sam-Cordry approved these changes

2023-10-28 21:58 UTC, Sam-Cordry commented on constitution.tex
> -Exceptions may be made at the discretion of the Evaluations Director.
Agreed, this looks good. I approve now that the other changes are not present.

2023-11-05 19:38 UTC, esoccoli commented
@rhochgraf21 can you review this again when you have a chance

2023-11-06 01:06 UTC, rhochgraf21 approved these changes

2023-11-06 01:06 UTC, merged