Updated list of active member priveledges
rhochgraf21/Constitution pull request #75
Opened 2023-10-28 02:46 UTC by esoccoli

Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):
Fixed bulleted list in 4.B.4 based on discussion during Tuesday's meeting

2023-10-28 02:47 UTC, mxmeinhold requested changes

2023-10-28 02:47 UTC, mxmeinhold commented on constitution.tex
> +iance with University Regulations}
Why is this on a new line? Document standard is a sentance per line

2023-10-31 01:16 UTC, esoccoli commented on constitution.tex
> +iance with University Regulations}
Fixed it

2023-10-31 02:42 UTC, rhochgraf21 commented on constitution.tex
> -	\item Reside on the House
👍  (is covered later)

2023-10-31 02:42 UTC, rhochgraf21 commented on constitution.tex
> +	\item Hold an E-Board position
👍

2023-10-31 02:42 UTC, rhochgraf21 commented on constitution.tex
> -	\item Receive priority for available housing on the House when returning from cooperative education
the (above line, about co-op return) seems important - can we work it into the below statement?

also might be good to mention "guaranteed housing" ... imo, the language in the below sentence may help back us up when talking to housing/reslife

2023-10-31 03:03 UTC, esoccoli commented on constitution.tex
> -	\item Receive priority for available housing on the House when returning from cooperative education
If i am remembering correctly, we don't guarantee housing, but we do give priority housing.

2023-11-01 01:25 UTC, rhochgraf21 commented on constitution.tex
> -	\item Receive priority for available housing on the House when returning from cooperative education
after discussion  👍 

is removing attend csh functions a space thing?

2023-11-06 22:39 UTC, esoccoli commented on constitution.tex
> -	\item Receive priority for available housing on the House when returning from cooperative education
No, it is because the majority of CSH events are not restricted only to members

2024-01-27 22:29 UTC, Qelxiros approved these changes
lgtm

2024-01-30 03:33 UTC, merged